#!/bin/bash

#pocet cisel bud zadam nebo 10 :)
if [ $# -lt 1 ];then 
    numbers=10;
else
    numbers=$1;
fi;

#preklad cpp zdrojaku
mpic++ --prefix /usr/local/share/OpenMPI -o oets odd-even.cpp


#vyrobeni souboru s random cisly
dd if=/dev/random bs=1 count=$numbers of=numbers >/dev/null 2>&1

#pocet procesoru pro bucket sort
if [ $numbers -gt 1 ]
then
	pom=$(echo 'l('$numbers')/l(2)'| bc -l)
	rou=$(echo $pom | awk '{print int($1)}')
	proc=$(($rou*2-1))
fi
if [ $numbers -eq 1 ]
then
	proc=$((1))
fi
if [ $numbers -lt 1 ]
then
	proc=$((0))
fi
#echo $proc
#spusteni
mpirun --prefix /usr/local/share/OpenMPI -np $proc oets

#uklid
rm -f oets numbers

