#!/bin/bash

#pocet cisel bud zadam nebo 10 :)
if [ $# -lt 1 ];then 
    numbers=10;
else
    numbers=$1;
fi;

#preklad cpp zdrojaku
mpic++ --prefix /usr/local/share/OpenMPI -o oets odd-even.cpp


#vyrobeni souboru s random cisly
dd if=/dev/random bs=1 count=$numbers of=numbers

#pocet procesoru pro bucket sort
pom=$(echo 'l('$numbers')/l(2)'| bc -l)
rou=$(echo $pom | awk '{print int($1)}')
proc=$(($rou*2-1))
#echo $proc
#spusteni
mpirun --prefix /usr/local/share/OpenMPI -np $proc oets

#uklid
rm -f oets numbers

